### ISSUE TITLE
can't connect to wifi

### ISSUE THREAD

**Issue by robomaniac** [930913/framework32#1]
I am super existed to try the octoprint demo but can't connect to wifi with the framework32.

I then test this simple wifi code to test my hardware
```
#include "WiFi.h"
 
const char* ssid = "yourNetworkName";
const char* password =  "yourNetworkPass";
 
void setup() {
 
  Serial.begin(115200);
 
  WiFi.begin(ssid, password);
 
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.println("Connecting to WiFi..");
  }
 
  Serial.println("Connected to the WiFi network");
 
}
 
void loop() {}
```

I tried this code with

1. home dual band router
2. LTE router
3. iphone hotspot

I can get my ESP32 TTGO to connect to all those devices.

I then copy the SSID and password to my config.h file and can't connect to wifi.

```
char configJson[4096] = R"CONFIG({
  "sleepTimeout": 20000,
  "rotation": 0,
  "screenBrightness": 255,
  // See https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv for timezone
  "timezone": "EST5EDT,M3.2.0,M11.1.0",
  "clockFormat": "%H:%M",
  "wifi": {
      "ssid": "yourNetworkName",
      "password": "yourNetworkPass"
   },
  "Octoprint": {
    "server": "http://192.168.1.182/",
    "apikey": "octo API",
    "sleepDisabled": true,
    "refreshTime": 5000
  }
})CONFIG";
```

I also tried the original config with 2 different wifi credential. I did not try to place all 3.

this config.h is with all my tabs at the top of arduino IDE. Also don't understand why you have a config.example.h file when you could just have config.h. I deleted the config.example.h from the IDE too.

**Comment by 930913** [comment]
I thought the library that parses the config would ignore the comment, but apparently not. Removing the comment like https://github.com/930913/framework32/pull/2/files should fix the problem. Thanks for reporting the issue.

The reason for the `config.h` and the `config.example.h`, is because I, and any contributor, have both - one for our personal credentials, and one for the example for everyone else to see. Obviously it would be bad if we were to accidentally commit our personal credentials, so it's added to the `.gitignore`

**Comment by robomaniac** [comment]
Thank you! Got octoprint working. Wifi connection on my board does not seems reliable/robust but at least it works!

**Comment by 930913** [comment]
Great to hear! Have you got four bars of WiFi?
